[package]
name = "chess-engine"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "chess-engine"
path = "src/main.rs"

[dependencies]
rand = "0.8"
tract-onnx = "0.21"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
panic = "abort"